name: context-resource
version: '0.1.0.0'
github: "jship/context/context-resource"
license: MIT
license-file: LICENSE.md
copyright: 2020 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: Thread-safe, pool-compatible resource provider
description: |
  A thread-safe, pool-compatible resource provider abstraction that supports
  resource-sharing within nested actions.
category: Data

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - base >=4.12 && <5
  - context >=0.0.0 && <1
  source-dirs: library

tests:
  context-resource-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - async
    - base
    - context
    - context-resource
    - hspec
