name: context-http-client
version: '0.2.0.0'
github: "jship/context/context-http-client"
license: MIT
license-file: LICENSE.md
copyright: 2020 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: Modify HTTP requests/responses using context
description: |
  Modify outgoing HTTP requests and incoming HTTP responses using context.
category: Web

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - base >=4.12 && <5
  - context >=0.2.0.0 && <0.3
  - http-client >=0.5.13.1 && <0.8
  source-dirs: library

tests:
  context-http-client-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - async
    - base
    - bytestring
    - case-insensitive
    - context
    - hspec
    - http-client
    - context-http-client
    - http-types
    - stm
    - wai
    - warp
