name: context
version: '0.1.1.0'
github: "jship/context"
license: MIT
license-file: LICENSE.md
copyright: 2020 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: Thread-indexed, nested contexts
description: |
  Thread-indexed storage around arbitrary context values. The interface supports
  nesting context values per thread, and at any point, the calling thread may
  ask for their current context.
category: Data

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - base >=4.12 && <5
  - containers >=0.6.0.1 && <0.7
  source-dirs: library

tests:
  context-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - async
    - base
    - ghc-prim
    - hspec
    - context
    ghc-options:
    - -threaded
