name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]
        resolver:
        - lts-16.3 # ghc-8.8

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'
    - name: Setup
      env:
        RESOLVER: ${{ matrix.resolver }}
      run: stack --resolver="$RESOLVER" --no-terminal setup
    - name: Build
      env:
        RESOLVER: ${{ matrix.resolver }}
      run: stack --resolver="$RESOLVER" --no-terminal build --pedantic --test --no-run-tests --bench --no-run-benchmarks
    - name: Test
      env:
        RESOLVER: ${{ matrix.resolver }}
      run: stack --resolver="$RESOLVER" --no-terminal build --pedantic --test
