name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]
        resolver:
        - lts-16.3 # ghc-8.8
    env:
      RESOLVER: ${{ matrix.resolver }}

    steps:
    - uses: actions/checkout@v3
    - id: haskell-actions-setup
      uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: latest
    - name: Cache
      uses: actions/cache@v3.0.1
      with:
        path: ${{ steps.haskell-actions-setup.outputs.stack-root }}
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(format('{0}.yaml', matrix.resolver)) }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.resolver }}-
          ${{ runner.os }}-
    - name: Install GHC
      run: stack --resolver="$RESOLVER" --no-terminal setup
    - name: Build Dependencies
      run: stack --resolver="$RESOLVER" --no-terminal build --only-dependencies
    - name: Build
      run: stack --resolver="$RESOLVER" --no-terminal build --pedantic --test --no-run-tests --bench --no-run-benchmarks --haddock --no-haddock-deps
    - name: Test
      run: stack --resolver="$RESOLVER" --no-terminal build --pedantic --test
